# Site settings
title: Graph Machine Learning Group
email: info@gmlg.ch
description: Research group part of the Swiss AI Lab (IDSIA) at UniversitÃ  della Svizzera italiana (Switzerland) led by Prof. Cesare Alippi.
url: https://gmlg.ch/

address: "<strong>UniversitÃ  della Svizzera italiana</strong><br>Via Giuseppe Buffi, 13 â€¢ 6900 Lugano â€¢ Switzerland"

navbar:
  brand:
    name: GMLG Lugano
    logo: assets/img/logo/logo.svg
  pages:
    - title: About
      url: /
      icon: ğŸ 
    - title: People
      url: /people.html
      icon: ğŸ‘¨â€ğŸ’»
    - title: Publications
      url: /publications.html
      icon: ğŸ“„

social:
  twitter: GMLG_Lugano
  github: Graph-Machine-Learning-Group
